# Generated by Django 5.0.2 on 2024-02-21 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busfee',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='student',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Mobile number must be exactly 10 digits.')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Mobile number must be exactly 10 digits.')]),
        ),
    ]
